name: OpenTofu CI

on:
  pull_request:
    branches: [main]
    paths:
      - '**/*.tf'
      - '**/*.tftest.hcl'
      - '.github/workflows/test.yml'

jobs:
  fmt-check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: opentofu/setup-opentofu@9d84900f3238fab8cd84ce47d658d25dd008be2f # v1.0.8
        with:
          tofu_version: "1.9"
      - name: OpenTofu Format Check
        run: tofu fmt -check -recursive

  validate:
    name: Validate
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        directory:
          - _shared/platform-context
          - vcluster
          - vcluster-kubeconfig
          - vcluster-platform-registration
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: opentofu/setup-opentofu@9d84900f3238fab8cd84ce47d658d25dd008be2f # v1.0.8
        with:
          tofu_version: "1.9"
      - name: OpenTofu Init
        working-directory: ${{ matrix.directory }}
        run: tofu init -backend=false
      - name: OpenTofu Validate
        working-directory: ${{ matrix.directory }}
        run: tofu validate

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        directory:
          - vcluster
          - vcluster-kubeconfig
          - vcluster-platform-registration
          - single-namespace-rename
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: opentofu/setup-opentofu@9d84900f3238fab8cd84ce47d658d25dd008be2f # v1.0.8
        with:
          tofu_version: "1.9"
      - name: OpenTofu Init
        working-directory: ${{ matrix.directory }}
        run: tofu init -backend=false
      - name: OpenTofu Test
        working-directory: ${{ matrix.directory }}
        run: tofu test -no-color
